# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: prepare wsl image for vscode

on: [push,workflow_dispatch]   

jobs:
    get_vscode:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: execute download
              id: download_vscode
              run: ./download_vscode.sh

            - name: add cache
              uses: actions/cache@v3
              with:
                key: ${{ steps.download_vscode.outputs.version_ref }}
                path: |
                  dist            
