# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: prepare wsl image for vscode

on: [push,workflow_dispatch]   

jobs:
    get_vscode:
        runs-on: ubuntu-latest
        steps:
            - name: Install podman
              uses: gacts/install-podman@v1

            - name: Checkout repo
              uses: actions/checkout@v4              

            - name: Execute download dependencies
              id: download_vscode
              run: ./download_vscode.sh

            - name: Build container image
              run: podman build --build-arg VSCODE_COMMIT_ID=${{ steps.download_vscode.commit_ref }} --build-arg VSCODE_VERSION=${{ steps.download_vscode.version_ref }} -t wsl_tmp

            - name: Run fresh images
              run: podman run wsl_tmp --name wsl_tmp cat /etc/os-release

            - name: Export container
              run: podman export wsl_tmp | tar cvzf dist/rocky8_wsl.tar.gz